import { Poppins } from "next/font/google";
import { CartProvider } from "@/data/CartContext"; 
import "./globals.css";

export const title = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Dil Karts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
    <link rel="icon" href="https://dilfoods.in/wp-content/uploads/2023/04/cropped-Dil-Foods-new-logo-32x32.png" sizes="32x32" />
    </head>
      <body className={title.className}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
