import { Poppins } from "next/font/google";
import { CartProvider } from "@/data/CartContext"; 
import "./globals.css";

export const title = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Dil Karts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={title.className}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
